### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by augnustin** [beatrichartz/parallel_stream#13]
Not a big deal but I have those warnings which rise when I compile my app:

```
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
  /app/deps/parallel_stream/mix.exs:17
==> parallel_stream
warning: Stream.chunk/4 is deprecated. Use Stream.chunk_every/4 instead
  lib/parallel_stream/producer.ex:16
Generated parallel_stream app
```

Trying to get rid of it.

**Comment by everettvody** [comment]
+1

**Comment by maennchen** [comment]
@beatrichartz Would it be possible to release the current master to hex to get rid of this warning?

**Comment by beatrichartz** [comment]
I'm probably going to get to this sometime in the next days. Will have to move CI from travis so it might take a bit.

**Comment by beatrichartz** [comment]
Got it all done, simpler than I thought. You should be able to pull `1.1.0`.
