### ISSUE TITLE
Deprecation warnings: "coveralls" and Stream.chunk/4 -> Stream.chunk_every/4 

### ISSUE THREAD

**Issue by drernie** [beatrichartz/parallel_stream#18]
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of ASCII letters, numbers, and underscores do not require quotes
  /Users/ernest/Developer/igwet/deps/parallel_stream/mix.exs:17:30

==> parallel_stream
Compiling 11 files (.ex)
warning: Stream.chunk/4 is deprecated. Use Stream.chunk_every/4 instead
  lib/parallel_stream/producer.ex:16: ParallelStream.Producer.build!/4

**Comment by GRoguelon** [comment]
Hi @drernie 

Both warnings were solved back in October 2021:
- `"coveralls"`: 4587fd8
- `Stream.chunk/4`: 939e4c2

You can update to the [latest version](https://hex.pm/packages/parallel_stream/1.1.0): `1.1.0`

**Comment by drernie** [comment]
Ah, thanks. Looks like the problem is that some of my other packages didn’t update your version. Will ping them.

You can close. Sorry for the confusion.
