### ISSUE TITLE
Possible to version bump and release?

### ISSUE THREAD

**Issue by mylanconnolly** [beatrichartz/parallel_stream#5]
I only ask because I'm getting a bunch of compiler warnings about the zero arity functions.

I was planning on fixing them and sending a pull request before I noticed that they were already fixed.

If you were waiting on adding some features before releasing a new version, I understand. Just thought I'd ask. Thanks!

**Comment by beatrichartz** [comment]
For sure it's possible to pull in the pr and release 👍 no worries, just send the pr my way and I'll do it.
